name: Main CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: instytutfi/estateguru-tax/.github/workflows/_test.yml@main
  deploy:
    name: Deploy
    needs: test
    uses: instytutfi/estateguru-tax/.github/workflows/_deploy.yml@main
